title: <p align="center"> Joanna Rashid </p>

logo: "/images/headshot_small.jpeg?raw=true" 

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/joannarashid/">LinkedIn</a> |
  <a href="https://github.com/joannarashid">GitHub</a>
  </p>
  I'm a San Francisco Bay Area based data scientist. I am all about scrutinizing data in pursuit of the big picture. I have just earned a Master of Science in Analytics, an interdisciplinary data science program, at Georgia Institute of Technology. I specialize in technical data analysis and visualization, statistical modeling, and machine learning. I am skilled in utilizing programming languages such as Python, SQL, and R and have demonstrated strong problem solving skills and expertise in transforming raw data into actionable insights.
  <br><br>
  “All models are wrong, some are useful.” -George Box 
  <br><br>
  </p>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-PZHPNDQQN7 # Google Analytics tracking ID
